name: myeddatestsite
favicon: null
layout_spectrum: 0.5382687367964536
typography_spectrum: 0.7803109658416361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.028384907636791468
  lightness: 0.9303799653425813
  saturation: 0.6536473010201007
  rhythmicContrast: 0.39862254657782614
purpose: []
